name: Mobile app

on:
  push:
    branches:
  pull_request:
    branches: [main]
  workflow_dispatch:
#f
#  github.event_name == 'pudl_requestw'edwexxdddd
jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-20.04
    env:
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

    steps:
      - uses: actions/checkout@v2

      - run: git log -1

      - run: echo $COMMIT_MESSAGE

      - run: echo "xddddd"
        if: contains(github.event.head_commit.message, '[e2e]')

      # - run: echo "${{ github.event.head_commit.message }}""
