name: Mobile app

on:
  push:
    branches:
  pull_request:
    branches: [main]
  workflow_dispatch:


#  github.event_name == 'pull_request'c

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-20.04
    # if: ${{ contains(github.event.head_commit.message, '[e2e]') || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2

      - run: git log -1

      - run: echo "${{ github.event_name }}"

      # - run: echo "${{ github.event.head_commit.message }}""
