name: Mobile app

on:
  push:
    branches:
  pull_request:
    branches: [main]
  workflow_dispatch:

#  github.event_name == 'pull_request' xd
jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-20.04
    if: ${{ contains(github.event.head_commit.message, '[e2e]') }}
    steps:
      - uses: actions/checkout@v2

      - run: echo xddd

      - run: git log -1

      - run: ${{ github.event.head_commit.message }}
