name: Mobile app

on:
  push:
    branches:
  pull_request:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    working-directory: app

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - run: echo xddd
