name: Mobile app

on:
  push:
    branches:
  pull_request:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    working-directory: app

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
          cache-dependency-path: app/yarn.lock

      - run: echo xddd
