name: Mobile app

on:
  push:
    branches:
  pull_request:
    branches: [main]
  workflow_dispatch:
#f
#  github.event_name == 'pudl_requestw'edwexxdddd
jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-20.04
    env:
      Xd: true

    steps:
      - uses: actions/checkout@v2

      - run: git log -1

      - run: echo $COMMIT_MESSAGE

      - run: echo "xddddd"
        if: $Xd
# contains(github.event.head_commit.message, '[e2e]') || github.ref == 'refs/heads/main'
# - run: echo "${{ githuxdb.event.head_commit.message }}""
