name: Mobile app

on:
  push:
    branches:
  pull_request:
    branches: [main]
  workflow_dispatch:
#f
#  github.event_name == 'pudl_requestw'edwexxrwddddxd
jobs:
  build-android:
    name: Build Android
    runs-on: macos
    # env:
    #   Xd: ${{ contains(github.event.head_commit.message, '[e2e]') || github.ref_protected || github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v2

    - name: Setup a local Compose stack
      run: docker-compose up --build -d

    # - name: Install VirtualBox
    #   run: brew install --cask virtualbox
    # - name: Restart docker machine
    #   run: |
    #     docker-machine create --driver virtualbox default
    #     docker-machine restart
    #     eval "$(docker-machine env default)"
    #     docker-machine restart
# contains(github.event.head_commit.message, '[e2e]') || github.ref == 'refs/heads/main'
# - run: echo "${{ githuxdb.event.head_commit.message }}""
